version: '3'
services:
  app:
    container_name: bulbul
    restart: always
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - '80:8000'
    volumes: 
      - ./:/usr/src/app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'